import { useCallback, useEffect, useState } from 'react';
import { View, Text, StyleSheet, FlatList, RefreshControl, Pressable, Alert } from 'react-native';
import { useRouter, useFocusEffect, Stack } from 'expo-router';
import { useAuth, ApiError } from '@/lib/auth-context';
import { api, Expense, Property } from '@/lib/api';
import { Screen, Card, EmptyState, LoadingScreen, SegmentedControl, ErrorBanner } from '@/components/ui';
import { PropertySelect } from '@/components/PropertySelect';
import { EXPENSE_CATEGORY_LABELS, EXPENSE_CATEGORY_ICONS } from '@/lib/status';
import { colors, spacing, typography } from '@/theme';
import { Ionicons } from '@expo/vector-icons';

type Range = 'MONTH' | 'ALL';

function currentMonth() {
  return new Date().toISOString().slice(0, 7); // YYYY-MM
}

export default function ExpensesScreen() {
  const { session } = useAuth();
  const router = useRouter();
  const [properties, setProperties] = useState<Property[]>([]);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [total, setTotal] = useState(0);
  const [range, setRange] = useState<Range>('MONTH');
  const [propertyFilter, setPropertyFilter] = useState<string | null>(null); // null = all
  const [isLoading, setIsLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  useEffect(() => {
    if (!session) return;
    api.properties.listMine(session.accessToken).then(setProperties);
  }, [session]);

  const load = useCallback(async () => {
    if (!session) return;
    setError(null);
    try {
      const month = range === 'MONTH' ? currentMonth() : undefined;
      const data = await api.expenses.list(
        { propertyId: propertyFilter ?? undefined, from: month, to: month },
        session.accessToken,
      );
      setExpenses(data.expenses);
      setTotal(data.total);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Could not load your expenses.');
    } finally {
      setIsLoading(false);
      setRefreshing(false);
    }
  }, [session, range, propertyFilter]);

  useFocusEffect(
    useCallback(() => {
      setIsLoading(true);
      load();
    }, [load]),
  );

  function confirmDelete(expense: Expense) {
    if (expense.isAutoGenerated) return;
    Alert.alert('Delete expense?', 'This can\'t be undone.', [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Delete', style: 'destructive', onPress: () => handleDelete(expense.id) },
    ]);
  }

  async function handleDelete(id: string) {
    if (!session) return;
    setError(null);
    setDeletingId(id);
    try {
      await api.expenses.remove(id, session.accessToken);
      await load();
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Could not delete this expense.');
    } finally {
      setDeletingId(null);
    }
  }

  if (isLoading) return <LoadingScreen />;

  return (
    <Screen>
      <Stack.Screen options={{ headerShown: true, title: '', headerBackTitle: 'Back' }} />
      <View style={styles.header}>
        <View style={{ flex: 1 }}>
          <Text style={typography.h1}>Expenses</Text>
          <Text style={[typography.bodyMuted, { marginTop: 2 }]}>
            {range === 'MONTH' ? 'This month' : 'All time'}
          </Text>
        </View>
        <Pressable onPress={() => router.push('/host/expense/new')} style={styles.addButton}>
          <Ionicons name="add" size={22} color={colors.white} />
        </Pressable>
      </View>

      <View style={{ paddingHorizontal: spacing.lg }}>
        <Card>
          <Text style={typography.bodyMuted}>Total</Text>
          <Text style={styles.totalValue}>{total.toFixed(0)} MAD</Text>
        </Card>

        <View style={{ marginTop: spacing.md }}>
          <SegmentedControl
            value={range}
            onChange={setRange}
            options={[
              { value: 'MONTH', label: 'This month' },
              { value: 'ALL', label: 'All time' },
            ]}
          />
        </View>

        <View style={{ marginTop: spacing.md }}>
          <PropertySelect
            label="Property"
            properties={properties}
            value={propertyFilter}
            onChange={setPropertyFilter}
            extraOptions={[
              { value: '__NONE__', label: 'All properties' },
              { value: 'GENERAL', label: 'General' },
            ]}
          />
        </View>

        {error && <ErrorBanner message={error} onRetry={load} />}
      </View>

      <FlatList
        data={expenses}
        keyExtractor={(item) => item.id}
        contentContainerStyle={styles.listContent}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} tintColor={colors.primary} />}
        ListEmptyComponent={
          <EmptyState
            message="No expenses logged for this view yet."
            actionLabel="Log an expense"
            onAction={() => router.push('/host/expense/new')}
          />
        }
        renderItem={({ item }) => (
          <Card style={{ marginBottom: spacing.sm }}>
            <View style={styles.row}>
              <View style={styles.iconCircle}>
                <Ionicons name={EXPENSE_CATEGORY_ICONS[item.category] as any} size={16} color={colors.primary} />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={typography.h3}>{EXPENSE_CATEGORY_LABELS[item.category]}</Text>
                <Text style={typography.bodyMuted}>{item.property?.name ?? 'General'}</Text>
                <Text style={typography.caption}>{new Date(item.date).toLocaleDateString()}</Text>
                {item.note && <Text style={[typography.bodyMuted, { marginTop: 2 }]}>{item.note}</Text>}
                {item.isAutoGenerated && (
                  <View style={styles.autoBadge}>
                    <Ionicons name="sync-outline" size={11} color={colors.inkFaint} />
                    <Text style={styles.autoBadgeText}>Auto-added from a completed cleaning</Text>
                  </View>
                )}
              </View>
              <View style={{ alignItems: 'flex-end' }}>
                <Text style={styles.amount}>{Number(item.amount).toFixed(0)} MAD</Text>
                {!item.isAutoGenerated && (
                  <Pressable onPress={() => confirmDelete(item)} disabled={deletingId === item.id} style={{ marginTop: spacing.xs }}>
                    <Ionicons name="trash-outline" size={16} color={deletingId === item.id ? colors.inkFaint : colors.danger} />
                  </Pressable>
                )}
              </View>
            </View>
          </Card>
        )}
      />
    </Screen>
  );
}

const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    gap: spacing.sm,
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  totalValue: { ...typography.h1, fontSize: 26, marginTop: 2 },
  listContent: { paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: spacing.xl },
  row: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm },
  iconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.successBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  amount: { fontWeight: '700', color: colors.ink, fontSize: 14 },
  autoBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: spacing.xs },
  autoBadgeText: { fontSize: 11, color: colors.inkFaint },
});
